name: HelloWorld
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.7"
settings:
  CODE_SIGN_IDENTITY: ""
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGNING_ALLOWED: NO
targets:
  HelloWorld:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.helloworld
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO
      SWIFT_VERSION: "5.0"
    info:
      path: HelloWorld.app/Info.plist
      properties:
        CFBundleDevelopmentRegion: zh_CN
        CFBundleDisplayName: HelloWorld
        CFBundleExecutable: HelloWorld
        CFBundleIdentifier: com.example.helloworld
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: HelloWorld
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIDeviceFamily: [1, 2]
        UIRequiredDeviceCapabilities: [arm64]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        MinimumOSVersion: "16.7"
